# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [3]:
import numpy as np
a = np.arange( 15 ).reshape( 5 , 3 )
print('list(a): ', list(a))
print('list()只會轉換陣列的第一層')
print('tolist(): ', a.tolist())
print('tolist()則會轉換陣列的所有層別')

list(a):  [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11]), array([12, 13, 14])]
list()只會轉換陣列的第一層
tolist():  [[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11], [12, 13, 14]]
tolist()則會轉換陣列的所有層別


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [9]:
# 記得先 Import 正確的套件

import numpy as np

In [13]:

a = np.random.randint(10, size=6) 
print(a)
print(a.ndim,'#表示陣列維度')
print(a.shape, '#表示每一維度的大小')
print(a.size, '#表示元素個數')
print(a.dtype, '#表示陣列中元素的型態')
print(a.itemsize, '#表示每一元素所佔空間')
print(len(a), '#表示陣列長度,非元素個數')
print(type(a), '#表示陣列型態')

[1 1 2 6 4 0]
1 #表示陣列維度
(6,) #表示每一維度的大小
6 #表示陣列長度
int32 #表示陣列中元素的型態
4 #表示每一元素所佔空間
6 #表示陣列長度
<class 'numpy.ndarray'> #表示陣列型態


In [12]:
b = np.random.randint(10, size=(3,4)) 
print(b)
print(b.ndim,'#表示陣列維度')
print(b.shape, '#表示每一維度的大小')
print(b.size, '#表示元素個數')
print(b.dtype, '#表示陣列中元素的型態')
print(b.itemsize, '#表示每一元素所佔空間')
print(len(b), '#表示陣列長度,非元素個數')
print(type(b), '#表示陣列型態')

[[2 0 8 7]
 [7 4 7 7]
 [2 1 2 2]]
2 #表示陣列維度
(3, 4) #表示每一維度的大小
12 #表示陣列長度
int32 #表示陣列中元素的型態
4 #表示每一元素所佔空間
3 #表示陣列長度
<class 'numpy.ndarray'> #表示陣列型態


In [15]:
c = np.random.randint(10, size=(2,3,2)) 
print(c)
print(c.ndim,'#表示陣列維度')
print(c.shape, '#表示每一維度的大小')
print(c.size, '#表示元素個數')
print(c.dtype, '#表示陣列中元素的型態')
print(c.itemsize, '#表示每一元素所佔空間')
print(len(c), '#表示陣列長度,非元素個數')
print(type(c), '#表示陣列型態')

[[[8 8]
  [3 5]
  [9 3]]

 [[0 4]
  [1 7]
  [8 2]]]
3 #表示陣列維度
(2, 3, 2) #表示每一維度的大小
12 #表示元素個數
int32 #表示陣列中元素的型態
4 #表示每一元素所佔空間
2 #表示陣列長度,非元素個數
<class 'numpy.ndarray'> #表示陣列型態


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [ ]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[7, 6, 7, 3, 7, 5]
[7, 6, 7, 3, 7, 5]


In [ ]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[array([5, 7, 4, 6]), array([9, 4, 0, 1]), array([9, 1, 2, 9])]


In [ ]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]
[array([[0, 4],
       [0, 1],
       [9, 5]]), array([[8, 7],
       [8, 2],
       [6, 0]])]


In [19]:
print(tolist(a))
print(tolist(b))
print(tolist(c))

[1, 1, 2, 6, 4, 0]
[[2, 0, 8, 7], [7, 4, 7, 7], [2, 1, 2, 2]]
[[[8, 8], [3, 5], [9, 3]], [[0, 4], [1, 7], [8, 2]]]


In [23]:
def list(index):
    return index.tolist()
print('透過function修改list功用')
print(list(a))
print(list(b))
print(list(c))

[1, 1, 2, 6, 4, 0]
[[2, 0, 8, 7], [7, 4, 7, 7], [2, 1, 2, 2]]
[[[8, 8], [3, 5], [9, 3]], [[0, 4], [1, 7], [8, 2]]]
